version: "3.1"
services:
  assistant:
    dns:
      - "192.168.127.1"
    build: .
    container_name: ii_assistent
    restart: unless-stopped
    volumes:
      - ./Thread:/app
      - ./audio:/audio
    ports:
      - "7676:7676/udp"
    links:
      - "rabbit:rabbit"
    command: ping 192.168.127.1
  rabbit:
    dns:
      - "192.168.127.1"
    image: rabbitmq:3.12-management
    container_name: rabbit
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
