version: "3.1"
services:
  assistant:
    dns:
      - "192.168.127.1"
    build: .
    container_name: ii_assistent
    restart: unless-stopped
    volumes:
      - ./Thread:/app
    ports:
      - "7676:7676"
    command: ping 192.168.127.1