version: "3.1"
services:
  assistant:
    dns:
      - "192.168.127.1"
    build: .
    container_name: ii_assistent
    restart: unless-stopped
    volumes:
      - ./Thread:/app
      - ./audio:/audio
    ports:
      - "7676:7676/udp"
    links:
      - "mongodb:mongodb"
    command: python server_thread_udp.py
  mongodb:
    image: mongodb/mongodb-enterprise-server:4.4.8-ubi8
    restart: unless-stopped
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_config:/data/configdb
      - mongodb_data:/data/db
volumes:
  mongodb_config:
  mongodb_data:
